services:
  table-factory:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        APP_UID: "${LOCAL_UID:-1000}"
        APP_GID: "${LOCAL_GID:-1000}"
    working_dir: /workspace
    volumes:
      - type: bind
        source: .
        target: /workspace
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    entrypoint:
      - table-factory
