from __future__ import annotations

import re
from collections import Counter
from pathlib import Path

import pytest
from conftest import invoke_cli

from table_factory.parser import parse_hive_ddl
from table_factory.type_mapper import map_hive_type

FIXTURES = Path(__file__).parent / "fixtures"
LARGE_DDL = FIXTURES / "large_show_create.sql"
COMMENTS_DDL = FIXTURES / "comments_and_partitions.sql"

ARTIFACT_ROLES = (
    "01_hive_create_physical",
    "02_hive_insert",
    "03_greenplum_create_external",
    "04_greenplum_create_physical",
    "05_greenplum_insert",
)

EXPECTED_LARGE_COLUMN_NAMES = tuple(f"column_{index:03d}" for index in range(1, 112))

LARGE_GREENPLUM_TYPES = {
    "STRING": "TEXT",
    "TIMESTAMP": "TIMESTAMP",
    "BIGINT": "BIGINT",
    "DECIMAL(38,12)": "NUMERIC(38,12)",
    "DECIMAL(38,0)": "NUMERIC(38,0)",
}


def _artifact_names(stem: str) -> tuple[str, ...]:
    return tuple(f"{stem}__{role}.sql" for role in ARTIFACT_ROLES)


def _read_artifacts(output_directory: Path) -> dict[str, str]:
    return {
        path.name: path.read_text(encoding="utf-8")
        for path in sorted(output_directory.glob("*.sql"))
        if path.is_file()
    }


def _generate(
    ddl: Path,
    output_directory: Path,
    *,
    repository_config: Path,
    cwd: Path,
) -> dict[str, str]:
    invoke_cli(
        "generate",
        "--input",
        ddl,
        "--output",
        output_directory,
        "--config",
        repository_config,
        cwd=cwd,
    )
    return _read_artifacts(output_directory)


def _normalized_type(data_type: str) -> str:
    return re.sub(r"\s+", "", data_type).upper()


def _modified_config(
    repository_config: Path,
    destination: Path,
    *replacements: tuple[str, str],
) -> Path:
    contents = repository_config.read_text(encoding="utf-8")
    for old, new in replacements:
        assert old in contents
        contents = contents.replace(old, new, 1)
    destination.write_text(contents, encoding="utf-8")
    return destination


def _hive_identifier_block(column_names: tuple[str, ...]) -> str:
    return ",\n".join(f"  `{name}`" for name in column_names)


def _greenplum_identifier_block(column_names: tuple[str, ...]) -> str:
    return ",\n".join(f'  "{name}"' for name in column_names)


def test_large_show_create_fixture_preserves_all_111_columns() -> None:
    ddl = LARGE_DDL.read_text(encoding="utf-8")
    tables = parse_hive_ddl(ddl)

    assert not ddl.rstrip().endswith(";")
    assert len(tables) == 1

    table = tables[0]
    assert table.database == "sample_source"
    assert table.name == "large_table"
    assert table.qualified_name == "sample_source.large_table"
    assert table.external is False
    assert table.create_sql == ddl.strip()
    assert table.partition_columns == ()
    assert table.comment is None

    assert len(table.columns) == 111
    assert tuple(column.name for column in table.columns) == EXPECTED_LARGE_COLUMN_NAMES
    assert all(column.comment is None for column in table.columns)
    assert Counter(_normalized_type(column.data_type) for column in table.columns) == {
        "STRING": 85,
        "TIMESTAMP": 22,
        "BIGINT": 1,
        "DECIMAL(38,12)": 2,
        "DECIMAL(38,0)": 1,
    }
    assert {
        column.name: _normalized_type(column.data_type)
        for column in table.columns
        if column.name in {"column_022", "column_088", "column_110", "column_111"}
    } == {
        "column_022": "DECIMAL(38,12)",
        "column_088": "DECIMAL(38,12)",
        "column_110": "BIGINT",
        "column_111": "DECIMAL(38,0)",
    }

    # The split Spark schema is deliberately present, but is not a schema source.
    assert "'spark.sql.sources.schema.numParts'='2'" in ddl
    assert "'spark.sql.sources.schema.part.0'=" in ddl
    assert "'spark.sql.sources.schema.part.1'=" in ddl
    assert "nullable" not in EXPECTED_LARGE_COLUMN_NAMES


def test_large_fixture_generates_exact_five_role_chain_deterministically(
    tmp_path: Path,
    repository_config: Path,
) -> None:
    output_directory = tmp_path / "generated"
    generated = _generate(
        LARGE_DDL,
        output_directory,
        repository_config=repository_config,
        cwd=tmp_path,
    )
    expected_names = _artifact_names("sample_source_large_table")

    assert tuple(generated) == expected_names
    assert all(
        generated[name].startswith("-- Generated by table-factory") for name in expected_names
    )

    table = parse_hive_ddl(LARGE_DDL.read_text(encoding="utf-8"))[0]
    column_names = tuple(column.name for column in table.columns)
    hive_definitions = ",\n".join(
        f"  `{column.name}` {column.data_type}" for column in table.columns
    )
    greenplum_definitions = ",\n".join(
        f'  "{column.name}" {LARGE_GREENPLUM_TYPES[_normalized_type(column.data_type)]}'
        for column in table.columns
    )
    hive_identifiers = _hive_identifier_block(column_names)
    greenplum_identifiers = _greenplum_identifier_block(column_names)

    hive_create = generated[expected_names[0]]
    assert (
        f"CREATE TABLE `target_hive_db`.`large_table_physical` (\n{hive_definitions}\n)"
    ) in hive_create
    assert "ROW FORMAT DELIMITED" in hive_create
    assert "FIELDS TERMINATED BY ','" in hive_create
    assert "ESCAPED BY '\\\\'" in hive_create
    assert "NULL DEFINED AS '\\\\N'" in hive_create
    assert "STORED AS TEXTFILE;" in hive_create
    for source_only_fragment in (
        "CREATE EXTERNAL TABLE",
        "PARTITIONED BY",
        "LOCATION",
        "ParquetHiveSerDe",
        "MapredParquetInputFormat",
        "MapredParquetOutputFormat",
        "TBLPROPERTIES",
        "spark.sql.",
        "hdfs://",
    ):
        assert source_only_fragment not in hive_create

    hive_insert = generated[expected_names[1]]
    assert (
        "INSERT INTO TABLE `target_hive_db`.`large_table_physical` "
        f"(\n{hive_identifiers}\n)\n"
        f"SELECT\n{hive_identifiers}\n"
        "FROM `sample_source`.`large_table`;"
    ) in hive_insert

    greenplum_external = generated[expected_names[2]]
    assert (
        f'CREATE EXTERNAL TABLE "ext"."large_table_ext" (\n{greenplum_definitions}\n)'
    ) in greenplum_external
    assert (
        "LOCATION (\n"
        "  'pxf://target_hive_db.large_table_physical?PROFILE=hive&SERVER=default'\n"
        ") ON ALL\n"
        "FORMAT 'CUSTOM' (FORMATTER='pxfwritable_import')\n"
        "ENCODING 'UTF8';"
    ) in greenplum_external
    assert "sample_source" not in greenplum_external
    assert "target_gp_database" not in greenplum_external

    greenplum_create = generated[expected_names[3]]
    assert (
        f'CREATE TABLE "dwh"."large_table" (\n{greenplum_definitions}\n)\nDISTRIBUTED RANDOMLY;'
    ) in greenplum_create
    assert "CREATE EXTERNAL TABLE" not in greenplum_create
    assert "PARTITIONED BY" not in greenplum_create
    assert "target_gp_database" not in greenplum_create

    greenplum_insert = generated[expected_names[4]]
    assert (
        'INSERT INTO "dwh"."large_table" '
        f"(\n{greenplum_identifiers}\n)\n"
        f"SELECT\n{greenplum_identifiers}\n"
        'FROM "ext"."large_table_ext";'
    ) in greenplum_insert

    all_sql = "\n".join(generated.values())
    assert "SELECT *" not in all_sql.upper()
    for legacy_command in (
        r"\bDROP\b",
        r"\bDESCRIBE\b",
        r"\bSHOW\s+CREATE\b",
        r"\bANALYZE\b",
        r"\bTRUNCATE\b",
    ):
        assert re.search(legacy_command, all_sql, flags=re.IGNORECASE) is None

    first_bytes = {name: (output_directory / name).read_bytes() for name in expected_names}
    regenerated = _generate(
        LARGE_DDL,
        output_directory,
        repository_config=repository_config,
        cwd=tmp_path,
    )
    second_bytes = {name: (output_directory / name).read_bytes() for name in expected_names}
    assert tuple(regenerated) == expected_names
    assert second_bytes == first_bytes
    assert not list(output_directory.glob("*.tmp"))


def test_comments_and_partition_columns_are_flattened_and_escaped(
    tmp_path: Path,
    repository_config: Path,
) -> None:
    table = parse_hive_ddl(COMMENTS_DDL.read_text(encoding="utf-8"))[0]

    assert table.external is True
    assert table.qualified_name == "source_db.events"
    assert table.comment == "События команды O'Brien"
    assert [(column.name, column.comment) for column in table.columns] == [
        ("event_id", "Идентификатор"),
        ("owner", "O'Brien"),
        ("amount", None),
    ]
    assert [(column.name, column.comment) for column in table.partition_columns] == [
        ("event_day", "День события")
    ]
    ordered_names = ("event_id", "owner", "amount", "event_day")
    assert tuple(column.name for column in table.all_columns) == ordered_names

    generated = _generate(
        COMMENTS_DDL,
        tmp_path / "comments output",
        repository_config=repository_config,
        cwd=tmp_path,
    )
    expected_names = _artifact_names("source_db_events")
    assert tuple(generated) == expected_names

    hive_create = generated[expected_names[0]]
    assert "CREATE TABLE `target_hive_db`.`events_physical`" in hive_create
    assert "`event_id` BIGINT COMMENT 'Идентификатор'" in hive_create
    assert "`owner` STRING COMMENT 'O\\'Brien'" in hive_create
    assert "`amount` DECIMAL(18, 2)" in hive_create
    assert "`event_day` DATE COMMENT 'День события'" in hive_create
    assert "COMMENT 'События команды O\\'Brien'" in hive_create
    assert "CREATE EXTERNAL TABLE" not in hive_create
    assert "PARTITIONED BY" not in hive_create
    assert "STORED AS PARQUET" not in hive_create
    assert "STORED AS TEXTFILE" in hive_create
    assert hive_create.index("`amount`") < hive_create.index("`event_day`")

    hive_identifiers = _hive_identifier_block(ordered_names)
    hive_insert = generated[expected_names[1]]
    assert (
        f"(\n{hive_identifiers}\n)\nSELECT\n{hive_identifiers}\nFROM `source_db`.`events`;"
    ) in hive_insert

    greenplum_identifiers = _greenplum_identifier_block(ordered_names)
    greenplum_external = generated[expected_names[2]]
    greenplum_create = generated[expected_names[3]]
    greenplum_insert = generated[expected_names[4]]
    for create_sql in (greenplum_external, greenplum_create):
        assert '"event_id" BIGINT' in create_sql
        assert '"owner" TEXT' in create_sql
        assert '"amount" NUMERIC(18,2)' in create_sql
        assert '"event_day" DATE' in create_sql
        assert create_sql.index('"amount"') < create_sql.index('"event_day"')
        assert "PARTITIONED BY" not in create_sql
        assert "O\\'Brien" not in create_sql
        assert "'События команды O''Brien'" in create_sql
        assert "'O''Brien'" in create_sql
        assert "'Идентификатор'" in create_sql
        assert "'День события'" in create_sql

    assert (
        "COMMENT ON TABLE \"ext\".\"events_ext\" IS 'События команды O''Brien';"
    ) in greenplum_external
    assert (
        'COMMENT ON COLUMN "ext"."events_ext"."event_day" IS \'День события\';'
    ) in greenplum_external
    assert (
        "COMMENT ON TABLE \"dwh\".\"events\" IS 'События команды O''Brien';"
    ) in greenplum_create
    assert ('COMMENT ON COLUMN "dwh"."events"."event_day" IS \'День события\';') in greenplum_create
    assert (
        "pxf://target_hive_db.events_physical?PROFILE=hive&SERVER=default"
    ) in greenplum_external
    assert (
        f'(\n{greenplum_identifiers}\n)\nSELECT\n{greenplum_identifiers}\nFROM "ext"."events_ext";'
    ) in greenplum_insert
    assert "SELECT *" not in hive_insert.upper()
    assert "SELECT *" not in greenplum_insert.upper()


@pytest.mark.parametrize(
    ("hive_type", "greenplum_type"),
    (
        ("sTrInG", "TEXT"),
        ("varchar ( 255 )", "VARCHAR(255)"),
        ("CHAR(7)", "CHAR(7)"),
        ("tinyint", "SMALLINT"),
        ("SMALLINT", "SMALLINT"),
        ("int", "INTEGER"),
        ("InTeGeR", "INTEGER"),
        ("bigint", "BIGINT"),
        ("FLOAT", "REAL"),
        ("real", "REAL"),
        ("double", "DOUBLE PRECISION"),
        ("double precision", "DOUBLE PRECISION"),
        ("decimal", "NUMERIC(10,0)"),
        ("numeric", "NUMERIC(10,0)"),
        ("decimal(12)", "NUMERIC(12,0)"),
        ("numeric ( 9 )", "NUMERIC(9,0)"),
        ("decimal(38, 12)", "NUMERIC(38,12)"),
        ("NuMeRiC ( 38 , 0 )", "NUMERIC(38,0)"),
        ("boolean", "BOOLEAN"),
        ("DATE", "DATE"),
        ("timestamp", "TIMESTAMP"),
    ),
)
def test_every_required_hive_type_mapping_is_explicit_and_case_insensitive(
    hive_type: str,
    greenplum_type: str,
) -> None:
    assert map_hive_type(hive_type) == greenplum_type


@pytest.mark.parametrize(
    "hive_type",
    (
        "ARRAY<STRING>",
        "MAP<STRING,INT>",
        "STRUCT<value:INT>",
        "UNIONTYPE<INT,STRING>",
        "VOID",
        "TIMESTAMP WITH LOCAL TIME ZONE",
        "MONEYISH",
    ),
)
def test_unverified_hive_types_are_never_silently_mapped_to_text(
    hive_type: str,
) -> None:
    with pytest.raises(ValueError) as captured:
        map_hive_type(hive_type)

    assert str(captured.value)


def test_unsupported_mapping_has_context_and_prevents_all_outputs(
    tmp_path: Path,
    repository_config: Path,
) -> None:
    input_directory = tmp_path / "input"
    input_directory.mkdir()
    (input_directory / "01_valid.sql").write_text(
        "CREATE TABLE source_db.valid_table (id BIGINT);\n",
        encoding="utf-8",
    )
    (input_directory / "02_unsupported.sql").write_text(
        "CREATE TABLE source_db.unsupported_table (id BIGINT, payload ARRAY<STRING>);\n",
        encoding="utf-8",
    )
    output_directory = tmp_path / "output"

    generate_result = invoke_cli(
        "generate",
        "--input",
        input_directory,
        "--output",
        output_directory,
        "--config",
        repository_config,
        cwd=tmp_path,
        check=False,
    )

    assert generate_result.returncode == 2
    for context in (
        "source_db.unsupported_table",
        "payload",
        "ARRAY<STRING>",
        "no lossless scalar mapping",
    ):
        assert context in generate_result.stderr
    assert not output_directory.exists()

    validate_result = invoke_cli(
        "validate",
        "--input",
        input_directory,
        "--config",
        repository_config,
        cwd=tmp_path,
        check=False,
    )
    assert validate_result.returncode == 2
    assert "source_db.unsupported_table" in validate_result.stderr
    assert "payload" in validate_result.stderr
    assert "ARRAY<STRING>" in validate_result.stderr
    assert not list(tmp_path.rglob("*.tmp"))


def test_two_tables_in_one_document_generate_two_complete_role_sets(
    tmp_path: Path,
    repository_config: Path,
) -> None:
    ddl = tmp_path / "two_tables.sql"
    ddl.write_text(
        "CREATE TABLE source_db.first_table (id BIGINT, label STRING);\n"
        "CREATE EXTERNAL TABLE source_db.second_table "
        "(created_at TIMESTAMP, amount DECIMAL(9,2));\n",
        encoding="utf-8",
    )
    output_directory = tmp_path / "output"

    generated = _generate(
        ddl,
        output_directory,
        repository_config=repository_config,
        cwd=tmp_path,
    )

    expected_names = tuple(
        filename
        for stem in ("source_db_first_table", "source_db_second_table")
        for filename in _artifact_names(stem)
    )
    assert tuple(generated) == expected_names
    assert len(generated) == 10
    assert all(content.strip() for content in generated.values())


def test_case_insensitive_multi_table_target_collision_writes_nothing(
    tmp_path: Path,
    repository_config: Path,
) -> None:
    ddl = tmp_path / "colliding_tables.sql"
    ddl.write_text(
        "CREATE TABLE source_db.Events (id BIGINT);\nCREATE TABLE source_db.events (id BIGINT);\n",
        encoding="utf-8",
    )
    output_directory = tmp_path / "output"

    result = invoke_cli(
        "generate",
        "--input",
        ddl,
        "--output",
        output_directory,
        "--config",
        repository_config,
        cwd=tmp_path,
        check=False,
    )

    assert result.returncode == 2
    assert "same Hive target" in result.stderr
    assert not output_directory.exists()


@pytest.mark.parametrize(
    ("ddl_text", "expected_target", "expected_source"),
    (
        (
            "CREATE TABLE target_hive_db.events_physical (id BIGINT);\n"
            "CREATE TABLE source_db.events (id BIGINT);\n",
            "target_hive_db.events_physical",
            "target_hive_db.events_physical",
        ),
        (
            "CREATE TABLE source_db.events (id BIGINT);\n"
            "CREATE TABLE target_hive_db.events_physical (id BIGINT);\n",
            "target_hive_db.events_physical",
            "target_hive_db.events_physical",
        ),
        (
            "CREATE TABLE TARGET_HIVE_DB.EVENTS_PHYSICAL (id BIGINT);\n"
            "CREATE TABLE source_db.Events (id BIGINT);\n",
            "target_hive_db.Events_physical",
            "TARGET_HIVE_DB.EVENTS_PHYSICAL",
        ),
    ),
)
def test_hive_target_cannot_overlap_any_source_table_in_batch(
    tmp_path: Path,
    repository_config: Path,
    ddl_text: str,
    expected_target: str,
    expected_source: str,
) -> None:
    ddl = tmp_path / "source_target_collision.sql"
    ddl.write_text(ddl_text, encoding="utf-8")
    output_directory = tmp_path / "output"

    result = invoke_cli(
        "generate",
        "--input",
        ddl,
        "--output",
        output_directory,
        "--config",
        repository_config,
        cwd=tmp_path,
        check=False,
    )

    assert result.returncode == 2
    assert (
        f"generated Hive target {expected_target} would collide with "
        f"source Hive table {expected_source} in the input batch"
    ) in result.stderr
    assert not output_directory.exists()


def test_hive_source_target_overlap_uses_unicode_normalization(
    tmp_path: Path,
    repository_config: Path,
) -> None:
    ddl = tmp_path / "unicode_source_target_collision.sql"
    decomposed_source_name = "Cafe\u0301"
    composed_target_name = "Café"
    ddl.write_text(
        f"CREATE TABLE target_hive_db.`{decomposed_source_name}` (id BIGINT);\n"
        f"CREATE TABLE `{composed_target_name}`.events (id BIGINT);\n",
        encoding="utf-8",
    )
    config = _modified_config(
        repository_config,
        tmp_path / "unicode_collision.yaml",
        (
            'physical_table_name_template: "{source_table}_physical"',
            'physical_table_name_template: "{source_database}"',
        ),
        (
            'external_table_name_template: "{source_table}_ext"',
            'external_table_name_template: "{source_database}_ext"',
        ),
        (
            'physical_table_name_template: "{source_table}"',
            'physical_table_name_template: "{source_database}"',
        ),
    )
    output_directory = tmp_path / "output"

    result = invoke_cli(
        "generate",
        "--input",
        ddl,
        "--output",
        output_directory,
        "--config",
        config,
        cwd=tmp_path,
        check=False,
    )

    assert result.returncode == 2
    assert f"generated Hive target target_hive_db.{composed_target_name}" in result.stderr
    assert f"source Hive table target_hive_db.{decomposed_source_name}" in result.stderr
    assert "in the input batch" in result.stderr
    assert not output_directory.exists()


def test_recursive_multiple_input_files_generate_ten_artifacts(
    tmp_path: Path,
    repository_config: Path,
) -> None:
    input_directory = tmp_path / "input"
    nested = input_directory / "nested"
    nested.mkdir(parents=True)
    (input_directory / "one.sql").write_text(
        "CREATE TABLE source_db.one_table (id BIGINT);",
        encoding="utf-8",
    )
    (nested / "two.SQL").write_text(
        "CREATE EXTERNAL TABLE source_db.two_table (label STRING);",
        encoding="utf-8",
    )

    result = invoke_cli(
        "generate",
        "--input",
        input_directory,
        "--output",
        tmp_path / "output",
        "--config",
        repository_config,
        cwd=tmp_path,
    )
    generated = _read_artifacts(tmp_path / "output")

    assert "Generated 10 SQL files" in result.stdout
    assert tuple(generated) == tuple(
        filename
        for stem in ("source_db_one_table", "source_db_two_table")
        for filename in _artifact_names(stem)
    )


def test_custom_filename_separator_keeps_stable_roles(
    tmp_path: Path,
    repository_config: Path,
) -> None:
    config = _modified_config(
        repository_config,
        tmp_path / "custom.yaml",
        ('filename_separator: "__"', 'filename_separator: "-"'),
    )

    generated = _generate(
        LARGE_DDL,
        tmp_path / "output",
        repository_config=config,
        cwd=tmp_path,
    )

    assert tuple(generated) == tuple(
        f"sample_source_large_table-{role}.sql" for role in ARTIFACT_ROLES
    )


def test_hive_overwrite_uses_explicit_select_without_unsupported_target_list(
    tmp_path: Path,
    repository_config: Path,
) -> None:
    config = _modified_config(
        repository_config,
        tmp_path / "overwrite.yaml",
        ("insert_mode: into", "insert_mode: overwrite"),
    )
    generated = _generate(
        COMMENTS_DDL,
        tmp_path / "output",
        repository_config=config,
        cwd=tmp_path,
    )

    hive_insert = generated[_artifact_names("source_db_events")[1]]
    ordered_columns = ("event_id", "owner", "amount", "event_day")
    assert hive_insert.endswith(
        "INSERT OVERWRITE TABLE `target_hive_db`.`events_physical`\n"
        "SELECT\n"
        f"{_hive_identifier_block(ordered_columns)}\n"
        "FROM `source_db`.`events`;\n"
    )
    assert "INSERT OVERWRITE TABLE `target_hive_db`.`events_physical` (" not in hive_insert
    assert "SELECT *" not in hive_insert.upper()


@pytest.mark.parametrize("table_name", ("orders-2026", "2026_orders"))
def test_backtick_source_names_work_with_default_target_templates(
    tmp_path: Path,
    repository_config: Path,
    table_name: str,
) -> None:
    ddl = tmp_path / "quoted_name.sql"
    ddl.write_text(
        f"CREATE TABLE source_db.`{table_name}` (id BIGINT);",
        encoding="utf-8",
    )
    generated = _generate(
        ddl,
        tmp_path / "output",
        repository_config=repository_config,
        cwd=tmp_path,
    )

    stem = f"source_db_{table_name}"
    assert tuple(generated) == _artifact_names(stem)
    assert (
        f"CREATE TABLE `target_hive_db`.`{table_name}_physical`"
        in generated[_artifact_names(stem)[0]]
    )
    assert f'CREATE TABLE "dwh"."{table_name}"' in generated[_artifact_names(stem)[3]]


@pytest.mark.parametrize(
    ("ddl_text", "message"),
    (
        (
            f"CREATE TABLE source_db.{'a' * 60} (id BIGINT);",
            "longer than 63 UTF-8 bytes",
        ),
        (
            f"CREATE TABLE source_db.events (`{'表' * 22}` STRING);",
            "longer than Greenplum's 63-byte identifier limit",
        ),
    ),
)
def test_greenplum_identifier_byte_limit_is_checked_before_write(
    tmp_path: Path,
    repository_config: Path,
    ddl_text: str,
    message: str,
) -> None:
    ddl = tmp_path / "long_identifier.sql"
    ddl.write_text(ddl_text, encoding="utf-8")
    output = tmp_path / "output"

    result = invoke_cli(
        "generate",
        "--input",
        ddl,
        "--output",
        output,
        "--config",
        repository_config,
        cwd=tmp_path,
        check=False,
    )

    assert result.returncode == 2
    assert message in result.stderr
    assert not output.exists()


def test_ordinary_and_partition_column_collision_is_rejected_before_write(
    tmp_path: Path,
    repository_config: Path,
) -> None:
    ddl = tmp_path / "duplicate_partition_column.sql"
    ddl.write_text(
        "CREATE TABLE source_db.events (id BIGINT, event_day STRING) "
        "PARTITIONED BY (`EVENT_DAY` DATE);",
        encoding="utf-8",
    )
    output = tmp_path / "output"

    result = invoke_cli(
        "generate",
        "--input",
        ddl,
        "--output",
        output,
        "--config",
        repository_config,
        cwd=tmp_path,
        check=False,
    )

    assert result.returncode == 2
    assert "colliding columns 'event_day' and 'EVENT_DAY'" in result.stderr
    assert "ordinary and partition columns must be unique" in result.stderr
    assert not output.exists()


def test_source_and_hive_target_collision_is_rejected_before_write(
    tmp_path: Path,
    repository_config: Path,
) -> None:
    ddl = tmp_path / "source.sql"
    ddl.write_text(
        "CREATE TABLE target_hive_db.same_table (id BIGINT);",
        encoding="utf-8",
    )
    config = _modified_config(
        repository_config,
        tmp_path / "collision.yaml",
        (
            'physical_table_name_template: "{source_table}_physical"',
            'physical_table_name_template: "{source_table}"',
        ),
    )
    output = tmp_path / "output"

    result = invoke_cli(
        "generate",
        "--input",
        ddl,
        "--output",
        output,
        "--config",
        config,
        cwd=tmp_path,
        check=False,
    )

    assert result.returncode == 2
    assert "source Hive table target_hive_db.same_table would collide" in result.stderr
    assert not output.exists()


def test_greenplum_external_and_physical_name_collision_is_rejected(
    tmp_path: Path,
    repository_config: Path,
) -> None:
    ddl = tmp_path / "source.sql"
    ddl.write_text(
        "CREATE TABLE source_db.events (id BIGINT);",
        encoding="utf-8",
    )
    config = _modified_config(
        repository_config,
        tmp_path / "collision.yaml",
        ("physical_schema: dwh", "physical_schema: ext"),
        (
            'external_table_name_template: "{source_table}_ext"',
            'external_table_name_template: "{source_table}"',
        ),
    )
    output = tmp_path / "output"

    result = invoke_cli(
        "generate",
        "--input",
        ddl,
        "--output",
        output,
        "--config",
        config,
        cwd=tmp_path,
        check=False,
    )

    assert result.returncode == 2
    assert "external and physical targets would have the same qualified name" in result.stderr
    assert not output.exists()
