from __future__ import annotations

import json
import re
from collections.abc import Sequence
from dataclasses import replace
from typing import Any

import pytest

from table_factory.config import FactoryConfig
from table_factory.errors import SemanticValidationError
from table_factory.generator import render_artifacts
from table_factory.parser import parse_hive_ddl


def _liquibase_artifact(ddl: str, config: FactoryConfig | None = None) -> str:
    table = parse_hive_ddl(ddl)[0]
    artifacts = render_artifacts(
        table,
        config=config or FactoryConfig(),
        source_label="source.sql",
    )
    return next(
        artifact.content for artifact in artifacts if artifact.filename.endswith("_liquibase.sql")
    )


def _payload(content: str) -> dict[str, Any]:
    match = re.search(r"\(E'(?P<payload>\{.*\})'\);\n\Z", content, re.DOTALL)
    assert match is not None
    payload = match.group("payload").replace("''", "'")
    payload = payload.replace("\\\\", "\\")
    value = json.loads(payload)
    assert isinstance(value, dict)
    return value


def test_liquibase_artifact_matches_the_platform_function_contract() -> None:
    content = _liquibase_artifact(
        "CREATE TABLE source_db.events ("
        "label STRING, amount DECIMAL(38,12), counter BIGINT, "
        "happened TIMESTAMP, event_day DATE"
        ");"
    )

    assert content.startswith(
        "--liquibase formatted sql\n"
        "-- Generated by table-factory from source.sql\n\n"
        "--changeset 22643610:stg-events_ext "
        "runOnChange:true splitStatements:false\n"
    )
    assert content.count("DROP EXTERNAL TABLE") == 1
    assert 'DROP EXTERNAL TABLE IF EXISTS "ext"."replica_events_ext" CASCADE;' in content
    assert 'SELECT "ext"."f_create_external_table"(' in content
    payload = _payload(content)
    assert payload == {
        "schema_name": "ext",
        "table_name": "replica_events_ext",
        "source_table": "original_hive_database.events",
        "columns": [
            {"name": "label", "type": "text", "description": "-"},
            {"name": "amount", "type": "numeric", "description": "-"},
            {"name": "counter", "type": "int8", "description": "-"},
            {"name": "happened", "type": "timestamp", "description": "-"},
            {"name": "event_day", "type": "date", "description": "-"},
        ],
    }


def test_subscription_and_original_database_drive_their_distinct_contracts() -> None:
    default = FactoryConfig()
    config = replace(
        default,
        greenplum=replace(
            default.greenplum,
            external_schema="s_adb_as_services_csoko_stg",
            replica="sapurp",
            subscription="pkap1121_sapurp_6",
            original_hive_database="internal_saperpuvhd_sapurp",
        ),
    )
    table = parse_hive_ddl(
        "CREATE EXTERNAL TABLE "
        "`prx_pkap1121_sapurp_6_internal_saperpuvhd_sapurp.mseg` "
        "(mandt STRING);"
    )[0]
    artifacts = render_artifacts(table, config=config, source_label="mseg.sql")
    liquibase = next(
        artifact.content for artifact in artifacts if artifact.filename.endswith("_liquibase.sql")
    )

    assert (
        "pxf://prx_pkap1121_sapurp_6_internal_saperpuvhd_sapurp."
        "replica_mseg_physical?PROFILE=hive&SERVER=default"
    ) in artifacts[2].content
    assert liquibase.startswith(
        "--liquibase formatted sql\n"
        "-- Generated by table-factory from mseg.sql\n\n"
        "--changeset 22643610:stg-mseg_ext runOnChange:true splitStatements:false\n"
        'DROP EXTERNAL TABLE IF EXISTS "s_adb_as_services_csoko_stg".'
        '"sapurp_mseg_ext" CASCADE;\n'
    )
    assert _payload(liquibase) == {
        "schema_name": "s_adb_as_services_csoko_stg",
        "table_name": "sapurp_mseg_ext",
        "source_table": "internal_saperpuvhd_sapurp.mseg",
        "columns": [{"name": "mandt", "type": "text", "description": "-"}],
    }


@pytest.mark.parametrize(
    ("hive_types", "expected"),
    [
        (("STRING", "VARCHAR(20)", "CHAR(3)"), ("text", "text", "text")),
        (("TINYINT", "SMALLINT", "INT", "BIGINT"), ("int2", "int2", "int4", "int8")),
        (("FLOAT", "REAL", "DOUBLE"), ("float4", "float4", "float8")),
        (("BOOLEAN", "DATE", "TIMESTAMP"), ("bool", "date", "timestamp")),
        (("DECIMAL", "NUMERIC(18,2)"), ("numeric", "numeric")),
    ],
)
def test_liquibase_payload_maps_every_supported_scalar_type(
    hive_types: Sequence[str],
    expected: Sequence[str],
) -> None:
    columns = ", ".join(f"column_{index} {data_type}" for index, data_type in enumerate(hive_types))

    payload = _payload(_liquibase_artifact(f"CREATE TABLE source_db.types ({columns});"))

    assert tuple(column["type"] for column in payload["columns"]) == tuple(expected)


def test_liquibase_payload_is_valid_json_inside_a_greenplum_string() -> None:
    expected_description = (
        "O'Brien \"quoted\" \\path\nline\t\\'; DROP TABLE victims; -- Кириллица 😀"
    )
    content = _liquibase_artifact(
        "CREATE TABLE source_db.events ("
        "`owner's` STRING COMMENT "
        "'O\\'Brien \"quoted\" \\\\path\\n"
        r"line\t\\\'; DROP TABLE victims; -- Кириллица 😀', "
        "empty_comment STRING COMMENT '', "
        "no_comment STRING"
        ");"
    )

    assert '"name": "owner\'\'s"' in content
    expected_sql_fragment = (
        json.dumps(expected_description, ensure_ascii=False)
        .replace("'", "''")
        .replace("\\", "\\\\")
    )
    assert 'SELECT "ext"."f_create_external_table"(E\'' in content
    assert expected_sql_fragment in content
    assert _payload(content)["columns"] == [
        {"name": "owner's", "type": "text", "description": expected_description},
        {"name": "empty_comment", "type": "text", "description": ""},
        {"name": "no_comment", "type": "text", "description": "-"},
    ]


def test_liquibase_description_rejects_nul() -> None:
    with pytest.raises(SemanticValidationError, match="contains NUL in a comment"):
        _liquibase_artifact(r"CREATE TABLE source_db.events (value STRING COMMENT '\0');")


def test_liquibase_marker_stays_first_when_source_comments_are_disabled() -> None:
    config = replace(
        FactoryConfig(), output=replace(FactoryConfig().output, include_source_comment=False)
    )

    content = _liquibase_artifact("CREATE TABLE source_db.events (id BIGINT);", config)

    assert content.startswith("--liquibase formatted sql\n\n--changeset ")


def test_changeset_template_rejects_unsafe_rendered_source_values() -> None:
    default = FactoryConfig()
    config = replace(
        default,
        hive=replace(default.hive, physical_table_name_template="safe_hive"),
        greenplum=replace(
            default.greenplum,
            external_table_name_template="safe_external",
            physical_table_name_template="safe_physical",
        ),
    )

    with pytest.raises(SemanticValidationError, match="produced unsafe changeset id"):
        _liquibase_artifact("CREATE TABLE source_db.`event name` (id BIGINT);", config)
