"""Artifact assembly, portable filenames, collisions, and safe writes."""

from __future__ import annotations

import os
import re
import tempfile
import unicodedata
from contextlib import suppress
from dataclasses import dataclass
from pathlib import Path

from table_factory.config import FactoryConfig
from table_factory.errors import OutputSafetyError, TableFactoryError
from table_factory.greenplum_renderer import (
    render_greenplum_create_external,
    render_greenplum_create_physical,
    render_greenplum_insert,
)
from table_factory.hive_renderer import (
    render_hive_create_physical,
    render_hive_insert,
)
from table_factory.liquibase_renderer import render_greenplum_create_external_liquibase
from table_factory.models import Table, TablePlan
from table_factory.naming import build_target_names
from table_factory.path_safety import has_untrusted_symlink_component
from table_factory.type_mapper import map_table_columns

_ARTIFACT_ROLES = (
    "01_hive_create_physical",
    "02_hive_insert",
    "03_greenplum_create_external",
    "03_greenplum_create_external_liquibase",
    "04_greenplum_create_physical",
    "05_greenplum_insert",
)
_MAX_STEM_BYTES = 160


@dataclass(frozen=True, slots=True)
class Artifact:
    """One pending output file."""

    filename: str
    content: str


def _safe_stem(table: Table) -> str:
    raw = table.qualified_name
    normalized = unicodedata.normalize("NFKC", raw)
    characters = [
        character if character.isalnum() or character in {"_", "-"} else "_"
        for character in normalized
    ]
    stem = re.sub(r"_+", "_", "".join(characters)).strip("._-")
    if not stem or stem in {".", ".."}:
        stem = "table"
    result: list[str] = []
    byte_count = 0
    for character in stem:
        encoded_length = len(character.encode("utf-8"))
        if byte_count + encoded_length > _MAX_STEM_BYTES:
            break
        result.append(character)
        byte_count += encoded_length
    return "".join(result) or "table"


def _safe_comment_text(value: str) -> str:
    return "".join(
        character if character.isprintable() and character not in "\r\n" else "_"
        for character in value
    )


def render_artifacts(
    table: Table | TablePlan,
    *,
    config: FactoryConfig,
    source_label: str,
) -> tuple[Artifact, ...]:
    """Render five workflow artifacts plus one alternative Liquibase wrapper."""
    plan = (
        table
        if isinstance(table, TablePlan)
        else TablePlan(
            source_label=source_label,
            source=table,
            targets=build_target_names(table, config),
            mapped_columns=map_table_columns(table),
        )
    )
    label_basename = source_label.replace("\\", "/").rsplit("/", maxsplit=1)[-1]
    safe_source_label = _safe_comment_text(label_basename)
    header = (
        f"-- Generated by table-factory from {safe_source_label}\n"
        if config.include_source_comment
        else ""
    )
    workflow_statements = (
        render_hive_create_physical(plan, config=config),
        render_hive_insert(plan, config=config),
        render_greenplum_create_external(plan, config=config),
        render_greenplum_create_physical(plan, config=config),
        render_greenplum_insert(plan),
    )
    liquibase_statement = render_greenplum_create_external_liquibase(plan, config=config)
    marker, newline, remainder = liquibase_statement.partition("\n")
    if marker != "--liquibase formatted sql" or not newline:
        raise AssertionError("Liquibase renderer omitted its required first line")
    contents = (
        *(header + statement for statement in workflow_statements[:3]),
        f"{marker}\n{header}{remainder}",
        *(header + statement for statement in workflow_statements[3:]),
    )
    stem = _safe_stem(plan.source)
    separator = config.filename_separator
    return tuple(
        Artifact(
            filename=f"{stem}{separator}{role}.sql",
            content=content,
        )
        for role, content in zip(_ARTIFACT_ROLES, contents, strict=True)
    )


def ensure_unique_artifacts(artifacts: list[Artifact]) -> None:
    """Reject inputs that would overwrite each other after safe-name normalization."""
    names: set[str] = set()
    duplicates: set[str] = set()
    for artifact in artifacts:
        comparison_name = unicodedata.normalize("NFKC", artifact.filename).casefold()
        if comparison_name in names:
            duplicates.add(artifact.filename)
        names.add(comparison_name)
    if duplicates:
        duplicate_list = ", ".join(sorted(duplicates))
        raise TableFactoryError(f"multiple tables map to the same output name: {duplicate_list}")


def _destination(output_directory: Path, filename: str) -> Path:
    if Path(filename).name != filename:
        raise OutputSafetyError("generated filename is not a plain filename")
    destination = output_directory / filename
    if destination.parent.resolve() != output_directory.resolve():
        raise OutputSafetyError("generated path would leave the output directory")
    return destination


def _reject_symlink_components(path: Path) -> None:
    """Reject an output path reached through a user-controlled symbolic link."""
    if has_untrusted_symlink_component(path):
        raise OutputSafetyError("output path must not contain a symbolic-link component")


def _unlink_error(path: str | Path) -> OSError | None:
    try:
        Path(path).unlink()
    except FileNotFoundError:
        return None
    except OSError as error:
        return error
    return None


def _write_staged_file(
    output_directory: Path,
    artifact: Artifact,
) -> str:
    descriptor: int | None = None
    temporary_name: str | None = None
    try:
        descriptor, temporary_name = tempfile.mkstemp(
            dir=output_directory,
            prefix=f".{artifact.filename}.",
            suffix=".tmp",
            text=True,
        )
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            descriptor = None
            handle.write(artifact.content)
            handle.flush()
            os.fsync(handle.fileno())
        return temporary_name
    except OSError as error:
        if descriptor is not None:
            with suppress(OSError):
                os.close(descriptor)
        cleanup_error = _unlink_error(temporary_name) if temporary_name is not None else None
        detail = error.strerror or "I/O error"
        if cleanup_error is not None:
            cleanup_detail = cleanup_error.strerror or "I/O error"
            detail = f"{detail}; temporary-file cleanup failed: {cleanup_detail}"
        raise OutputSafetyError(
            f"cannot stage generated file {artifact.filename}: {detail}"
        ) from None


def _unused_backup_name(output_directory: Path, filename: str) -> str:
    descriptor, backup_name = tempfile.mkstemp(
        dir=output_directory,
        prefix=f".{filename}.",
        suffix=".bak",
    )
    os.close(descriptor)
    Path(backup_name).unlink()
    return backup_name


def _reject_input_aliases(
    destinations: list[tuple[Artifact, Path]],
    input_paths: tuple[Path, ...],
) -> None:
    """Reject any destination that names the same file as a source DDL."""
    for artifact, destination in destinations:
        for input_path in input_paths:
            try:
                aliases_input = os.path.samefile(destination, input_path)
            except FileNotFoundError:
                aliases_input = False
            except OSError as error:
                detail = error.strerror or "I/O error"
                raise OutputSafetyError(
                    "cannot verify whether generated file "
                    f"{artifact.filename} aliases an input SQL file: {detail}"
                ) from None
            if aliases_input:
                raise OutputSafetyError(
                    "refusing to overwrite an input SQL file with generated artifact "
                    f"{artifact.filename}"
                )


def write_artifacts(
    output_directory: Path,
    artifacts: list[Artifact],
    *,
    input_paths: tuple[Path, ...] = (),
) -> None:
    """Replace the complete artifact set with rollback on any write failure."""
    _reject_symlink_components(output_directory)

    destinations: list[tuple[Artifact, Path]] = []
    for artifact in artifacts:
        destination = _destination(output_directory, artifact.filename)
        if destination.is_dir() and not destination.is_symlink():
            raise OutputSafetyError(
                f"cannot write generated file {artifact.filename}: destination is a directory"
            )
        destinations.append((artifact, destination))
    _reject_input_aliases(destinations, input_paths)

    try:
        output_directory.mkdir(parents=True, exist_ok=True)
    except OSError as error:
        raise OutputSafetyError(f"cannot create output directory: {error.strerror}") from None
    _reject_symlink_components(output_directory)
    if not output_directory.is_dir():
        raise OutputSafetyError("output path is not a directory")

    staged: list[tuple[Artifact, Path, str]] = []
    backups: list[tuple[Path, str]] = []
    committed: list[Path] = []
    current_filename = "artifact set"
    completed = False
    failure: OutputSafetyError | None = None
    try:
        for artifact, destination in destinations:
            current_filename = artifact.filename
            staged.append(
                (
                    artifact,
                    destination,
                    _write_staged_file(output_directory, artifact),
                )
            )

        for artifact, destination in destinations:
            if not os.path.lexists(destination):
                continue
            current_filename = artifact.filename
            backup_name = _unused_backup_name(
                output_directory,
                artifact.filename,
            )
            os.replace(destination, backup_name)
            backups.append((destination, backup_name))

        for artifact, destination, temporary_name in staged:
            current_filename = artifact.filename
            os.replace(temporary_name, destination)
            committed.append(destination)
        completed = True
    except (OSError, OutputSafetyError) as error:
        rollback_error: OSError | None = None
        for destination in reversed(committed):
            try:
                destination.unlink()
            except OSError as cleanup_error:
                rollback_error = rollback_error or cleanup_error
        for destination, backup_name in reversed(backups):
            try:
                os.replace(backup_name, destination)
            except OSError as restore_error:
                rollback_error = rollback_error or restore_error

        if isinstance(error, OutputSafetyError):
            detail = str(error)
        else:
            detail = error.strerror or "I/O error"
        if rollback_error is not None:
            rollback_detail = rollback_error.strerror or "I/O error"
            detail = f"{detail}; rollback failed: {rollback_detail}"
        failure = OutputSafetyError(f"cannot write generated file {current_filename}: {detail}")

    cleanup_failures: list[str] = []
    for artifact, _destination_path, temporary_name in staged:
        unlink_failure = _unlink_error(temporary_name)
        if unlink_failure is not None:
            cleanup_detail = unlink_failure.strerror or "I/O error"
            cleanup_failures.append(f"{artifact.filename}: {cleanup_detail}")
    if completed:
        for destination, backup_name in backups:
            unlink_failure = _unlink_error(backup_name)
            if unlink_failure is not None:
                cleanup_detail = unlink_failure.strerror or "I/O error"
                cleanup_failures.append(f"{destination.name}: {cleanup_detail}")

    if cleanup_failures:
        cleanup_detail = "; ".join(cleanup_failures)
        if failure is None:
            failure = OutputSafetyError(
                f"generated files were replaced, but transaction cleanup failed: {cleanup_detail}"
            )
        else:
            failure = OutputSafetyError(f"{failure}; cleanup failed: {cleanup_detail}")
    if failure is not None:
        raise failure from None
