"""Deterministic SQL artifact rendering and safe filesystem writes."""

from __future__ import annotations

import os
import re
import tempfile
import unicodedata
from contextlib import suppress
from dataclasses import dataclass
from pathlib import Path

from table_factory.config import FactoryConfig
from table_factory.errors import OutputSafetyError, TableFactoryError
from table_factory.models import Table

_ARTIFACT_NAMES = ("create", "drop", "describe", "show-create", "analyze")
_MAX_STEM_BYTES = 160


@dataclass(frozen=True, slots=True)
class Artifact:
    """One pending output file."""

    filename: str
    content: str


def _quote(identifier: str) -> str:
    return f"`{identifier.replace('`', '``')}`"


def _qualified(table: Table) -> str:
    if table.database:
        return f"{_quote(table.database)}.{_quote(table.name)}"
    return _quote(table.name)


def _safe_stem(table: Table) -> str:
    raw = table.qualified_name
    normalized = unicodedata.normalize("NFKC", raw)
    characters = [
        character if character.isalnum() or character in {"_", "-"} else "_"
        for character in normalized
    ]
    stem = re.sub(r"_+", "_", "".join(characters)).strip("._-")
    if not stem or stem in {".", ".."}:
        stem = "table"
    result: list[str] = []
    byte_count = 0
    for character in stem:
        encoded_length = len(character.encode("utf-8"))
        if byte_count + encoded_length > _MAX_STEM_BYTES:
            break
        result.append(character)
        byte_count += encoded_length
    return "".join(result) or "table"


def _safe_comment_text(value: str) -> str:
    return "".join(
        character if character.isprintable() and character not in "\r\n" else "_"
        for character in value
    )


def render_artifacts(
    table: Table,
    *,
    config: FactoryConfig,
    source_label: str,
) -> tuple[Artifact, ...]:
    """Render the five standard Hive operations for a parsed table."""
    qualified = _qualified(table)
    safe_source_label = _safe_comment_text(source_label)
    header = (
        f"-- Generated by table-factory from {safe_source_label}\n"
        if config.include_source_comment
        else ""
    )
    columns = ",\n".join(f"  {_quote(column.name)} {column.data_type}" for column in table.columns)
    create_statement = table.create_sql.strip() if table.create_sql else ""
    if create_statement:
        if not create_statement.endswith(";"):
            create_statement += ";"
        create_statement += "\n"
    else:
        create_statement = f"CREATE TABLE IF NOT EXISTS {qualified} (\n{columns}\n);\n"
    statements = {
        "create": create_statement,
        "drop": f"DROP TABLE IF EXISTS {qualified};\n",
        "describe": f"DESCRIBE {qualified};\n",
        "show-create": f"SHOW CREATE TABLE {qualified};\n",
        "analyze": f"ANALYZE TABLE {qualified} COMPUTE STATISTICS;\n",
    }
    stem = _safe_stem(table)
    separator = config.filename_separator
    return tuple(
        Artifact(
            filename=f"{stem}{separator}{name}.sql",
            content=header + statements[name],
        )
        for name in _ARTIFACT_NAMES
    )


def ensure_unique_artifacts(artifacts: list[Artifact]) -> None:
    """Reject inputs that would overwrite each other after safe-name normalization."""
    names: set[str] = set()
    duplicates: set[str] = set()
    for artifact in artifacts:
        comparison_name = unicodedata.normalize("NFKC", artifact.filename).casefold()
        if comparison_name in names:
            duplicates.add(artifact.filename)
        names.add(comparison_name)
    if duplicates:
        duplicate_list = ", ".join(sorted(duplicates))
        raise TableFactoryError(f"multiple tables map to the same output name: {duplicate_list}")


def _destination(output_directory: Path, filename: str) -> Path:
    if Path(filename).name != filename:
        raise OutputSafetyError("generated filename is not a plain filename")
    destination = output_directory / filename
    if destination.parent.resolve() != output_directory.resolve():
        raise OutputSafetyError("generated path would leave the output directory")
    return destination


def write_artifacts(output_directory: Path, artifacts: list[Artifact]) -> None:
    """Atomically write artifacts without following existing output symlinks."""
    if output_directory.is_symlink():
        raise OutputSafetyError("output directory must not be a symbolic link")
    try:
        output_directory.mkdir(parents=True, exist_ok=True)
    except OSError as error:
        raise OutputSafetyError(f"cannot create output directory: {error.strerror}") from None
    if not output_directory.is_dir():
        raise OutputSafetyError("output path is not a directory")

    for artifact in artifacts:
        destination = _destination(output_directory, artifact.filename)
        descriptor: int | None = None
        temporary_name: str | None = None
        try:
            descriptor, temporary_name = tempfile.mkstemp(
                dir=output_directory,
                prefix=f".{artifact.filename}.",
                suffix=".tmp",
                text=True,
            )
            with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
                descriptor = None
                handle.write(artifact.content)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary_name, destination)
            temporary_name = None
        except OSError as error:
            raise OutputSafetyError(
                f"cannot write generated file {artifact.filename}: {error.strerror}"
            ) from None
        finally:
            if descriptor is not None:
                os.close(descriptor)
            if temporary_name is not None:
                with suppress(FileNotFoundError):
                    Path(temporary_name).unlink()
